name: Practicee
version: '1.0-DeveloperBeta'
main: org.coderinlinux.practicee.Practicee
api-version: '1.0'

commands:
  enrich:
    description: make you rich
    usage: /enrich
  kit:
    description: you have one kit
    usage: /kit
  fly:
    description: a fly command
    usage: /fly
  spawn:
    description: a simple spawn
  report:
    usage: /report <player> <reason>
  help:
    usage: /help
  compass:
    description: simple command compass